services:
  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - laravel-network

  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: laravel_php
    restart: unless-stopped
    volumes:
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK';"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - laravel-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: laravel_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-laravel}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel} -d ${DB_DATABASE:-laravel}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - laravel-network

volumes:
  postgres_data:

networks:
  laravel-network:
    driver: bridge
